export const GuestConstants = {
    FIRST_NAME_MIN_LENGTH: 3,
    FIRST_NAME_MAX_LENGTH: 50,
    LAST_NAME_MIN_LENGTH: 3,
    LAST_NAME_MAX_LENGTH: 50,
    EMAIL_MAX_LENGTH: 100,
    STREET_MAX_LENGTH: 100,
    CITY_MAX_LENGTH: 50,
    COUNTRY_MAX_LENGTH: 50,
};