export const HotelConstants = {
    MAX_NAME_LENGTH: 100,
    MAX_DESCRIPTION_LENGTH: 500,
    MAX_PHONE_LENGTH: 15,
    MAX_CITY_LENGTH: 50,
    MAX_COUNTRY_LENGTH: 50,
    MAX_PHONE_NUMBER_LENGTH: 9,
    MAX_EMAIL_LENGTH: 100,
};